# Generated by Django 6.0.3 on 2026-03-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triangulo', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('chave_roda', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('estepe', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('kit_ferramenta_estepe', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('macaco', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('extintor', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('baterias', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('cartao_abastecimento', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('sistema_iluminacao', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('sistema_sinalizacao', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('retrovisores', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('estribo', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('intermitente', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('radio_comunicacao', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('tapetes', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('equipamento_som', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('quebra_mato', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('cinto_seguranca', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('direcao', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('calotas', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('palheta_limpador', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('painel', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('ignicao', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('ar_condicionado', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('manuais', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('sistema_motor', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('sistema_injecao', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('sistema_refrigeracao', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('chave_ignicao', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('botoes_vidro', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('tablet', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('drive', models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=10)),
                ('km', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='viaturas/')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='checklist/')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='viaturas.checklist')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='viatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viaturas.viatura'),
        ),
    ]
