# Generated by Django 6.0.3 on 2026-03-11 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0002_checklist_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='ar_condicionado',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='baterias',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='botoes_vidro',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='calotas',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='cartao_abastecimento',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='chave_ignicao',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='chave_roda',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='cinto_seguranca',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='direcao',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='drive',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='equipamento_som',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='estepe',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='estribo',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='extintor',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='ignicao',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='intermitente',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='kit_ferramenta_estepe',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='macaco',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='manuais',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='painel',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='palheta_limpador',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='quebra_mato',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='radio_comunicacao',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='retrovisores',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sistema_iluminacao',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sistema_injecao',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sistema_motor',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sistema_refrigeracao',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sistema_sinalizacao',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='tablet',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='tapetes',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='triangulo',
            field=models.CharField(choices=[('ok', 'OK'), ('nao_possui', 'Não possui'), ('alteracao', 'Alteração')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Policial'),
        ),
    ]
