# Generated by Django 6.0.3 on 2026-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0003_alter_checklist_ar_condicionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='modelo',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
    ]
