# Generated by Django 6.0.3 on 2026-03-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0004_viatura_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='km',
            field=models.IntegerField(blank=True, null=True, verbose_name='KM da Viatura'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='troca_oleo',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', verbose_name='Troca de óleo'),
        ),
    ]
