# Generated by Django 6.0.3 on 2026-03-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0005_checklist_km_checklist_troca_oleo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='troca_oleo',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=80, verbose_name='Troca de óleo'),
        ),
    ]
