# Generated by Django 6.0.3 on 2026-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0007_alter_checklist_troca_oleo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='km',
        ),
        migrations.AddField(
            model_name='checklist',
            name='km_atual',
            field=models.IntegerField(blank=True, null=True, verbose_name='KM Atual da Viatura'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='km_troca_oleo',
            field=models.IntegerField(blank=True, null=True, verbose_name='KM da Próxima Troca de Óleo'),
        ),
    ]
